# [[provider]]
# provider = "Github"
# authorization_url = "https://github.com/login/oauth/authorize"
# token_exchange_url = "https://github.com/login/oauth/access_token"
# app_id = "your_github_app_id"
# app_secret = "your_github_app_secret"
# scope = "read:user user:email"
# op_auth_string = "oidc/github"
# op = "github"

# [[provider]]
# provider = "Gitlab"
# authorization_url = "https://gitlab.com/oauth/authorize"
# token_exchange_url = "https://gitlab.com/oauth/token"
# app_id = "your_gitlab_app_id"
# app_secret = "your_gitlab_app_secret"
# scope = "read_user"
# op_auth_string = "oidc/gitlab"
# op = "gitlab"

# [[provider]]
# provider = "Google"
# authorization_url = "https://accounts.google.com/o/oauth2/v2/auth"
# token_exchange_url = "https://oauth2.googleapis.com/token"
# app_id = "your_google_app_id"
# app_secret = "your_google_app_secret"
# scope = "openid email profile"
# op_auth_string = "oidc/google"
# op = "google"

# [[provider]]
# provider = "Facebook"
# authorization_url = "https://www.facebook.com/v13.0/dialog/oauth"
# token_exchange_url = "https://graph.facebook.com/v13.0/oauth/access_token"
# app_id = "your_facebook_app_id"
# app_secret = "your_facebook_app_secret"
# scope = "public_profile"
# op_auth_string = "oidc/facebook"
# op = "facebook"

[[provider]]
provider = "Custom"
authorization_url = "https://dex-mock-server.example.org/dex/auth"
token_exchange_url = "https://dex-mock-server.example.org/dex/token"
app_id = "sctgdesk-api-server"
app_secret = "appsecret"
op_auth_string = "oidc/dex"
op = "dex"
scope = "openid email profile"