[s3config]
Endpoint = "https://compat.objectstorage.eu-london-1.oraclecloud.com"
Region = "eu-london-1"
AccessKey = "c324ead11faa0d87337c07ddc4a1129fab76188d"
SecretKey = "GJurV55f/LD36kjZFpchZMj/uvgTqxHyFkBchUUa8KA="
Bucket = "aezoz24elapn"
Windows64Key = "master/sctgdesk-releases/sctgdesk-1.2.6-x86_64.exe"
Windows32Key = "master/sctgdesk-releases/sctgdesk-1.2.6-i686.exe"
OSXKey = "master/sctgdesk-releases/sctgdesk-1.2.6.dmg"
OSXArm64Key = "master/sctgdesk-releases/sctgdesk-1.2.6.dmg"
IOSKey = "master/sctgdesk-releases/sctgdesk-1.2.6.ipa"